### PR TITLE
Feature/timestamp support

### PR DESCRIPTION
**Pull request by Prinkesh**
* Added Support for TImeStamp Support for XAxis . 
* TIme Input should be in microseconds 
* Fixed API bugs for double api

### CODE REVIEW

**Comment by Prinkesh** [comment]
Related Issue #34

**Comment by epezent** [comment]
Awesome! I'll try to get to this in the next day or so. Can you post some GIFs in the meantime.

**Comment by epezent** [comment]
@Prinkesh , I am unable to try this code due to a build error (MSVC):  `Cannot open include file: 'sys/time.h': No such file or directory`

Otherwise, my feedback is:
1) Move `TimeFormatter` into `implot.cpp`. We don't want an extra header for this.
2) Remove all C++11 headers and containers (`std::string` is problematic in particular)
3) Find a portable alternative for `sys/time.h`

I still think this is a necessary feature. Please post GIFs so we can see how this works. Thanks!

**Comment by epezent** [comment]
Sorry for the close. This was an unintended side-effect of deleting the double branch. Please resubmit.

**Pull request closed without merging**
