### PR TITLE
IsPlotItemHighlight, IsPlotXAxisHovered, IsPlotYAxisHovered

### PR DESCRIPTION
**Pull request by ozlb**
Returns true if plot item is highlight

PS: how to force "highlight"? Push or SetNext?

### CODE REVIEW

**Comment by ozlb** [comment]
IsPlotXAxisHovered, IsPlotYAxisHovered introduced to handle drag & drop over y axis.

Peek 2020-07-14 23-42

**Comment by epezent** [comment]
Really cool! I like this addition. You may have noticed activity as slowed down the past few weeks. I'm currently busy with PhD research and job interviews, but hopefully I'll have some time to review this next week. Feel free to continue improving this PR until then. Sorry for the delay!

**Comment by epezent** [comment]
Merged. I made a slight stylistic change to the way drag and drop rects are rendered, and changed some of the logic in `IsPlotXAxisHovered` and `IsPlotYAxisHovered`. 

dnd

**Comment by ozlb** [comment]
About ‘IsLegendEntryHovered’, i was recently considering to Push state of Highlight, what do you think?

**Pull request merged**
