### PR TITLE
AlignedPlots: Y/X axis padding over multiple plots

### PR DESCRIPTION
**Pull request by ozlb**
To have same Y axis padding, `ImPlot::BeginSubPlots()` must be called before 1st `ImPlot::BeginPlot()` and `ImPlot::EndSubPlots()` must be called after last `ImPlot::EndPlot()`. 
Peek 2020-11-10 22-44

https://github.com/epezent/implot/issues/53#issuecomment-723526658

### CODE REVIEW

**Comment by ozlb** [comment]
@epezent 
This is a working draft; final version requires a SubPlot ID pool to have the possibility to handle multiple sub plots. Thoughts?

**Comment by epezent** [comment]
@ozlb, thanks for looking into this. A few questions:

- Yes, I think you'll need a pool which stores padding information. You'll need to add either a string or int ID to the function signature to do this. I suggest adding a new struct to implot_internal.h that stores all the necessary state information. 
- In your example, the top plot has the widest labels, and so it propagates to the bottom plot in one frame. In the reverse case, the top plot won't update until the next frame. How noticeable is the delay? Can you show an example where the bottom plot has the widest labels?
- Can you show an example with auxiliary y-axis? 
- What happens when a plot has an axis title?
- What happens when a plot has neither an axis title or tick labels?
- After thinking about it, I think we might want to change the name of this function to `BeginAlignedLabels`/`EndAlignedLabels`. I think `BeginSubplot` would need to offer additional functionality to warrant the name, e.g. similar to [matplotlib subplots](https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.pyplot.subplot.html). That of course is also an option, but I think plots inside of ImGui Tables pretty much covers most use cases already. (e.g. grids of plots).

**Comment by ozlb** [comment]
- new signature with ID: i already implemented and i will post updates asap
- bottom to top propagation: the delay is only for a single cycle because on the next one if padding will not change it will match the saved. I can’t see delays. I will capture and share asap
- I’m regularly testing with 3 y axis, no problem. I will capture and share asap
- axis labels or tick labels and ticks are calculated before at plot bb (3), so are included. I will capture and share asap
- i renamed in BeginAlignedPlots

Thanks for your help

**Comment by epezent** [comment]
Awesome! One other thing: can we add support for vertical alignment when `ImGui::SameLine()` is used?

**Comment by ozlb** [comment]
Peek 2020-11-11 23-32

**Comment by ozlb** [comment]
> Awesome! One other thing: can we add support for vertical alignment when `ImGui::SameLine()` is used?

I changed signature of function to handle vertically/horizontally using already existing enum `ImPlotOrientation`. 

Peek 2020-11-12 00-26

Thoughts?

**Comment by epezent** [comment]
> I changed signature of function to handle vertically/horizontally using already existing enum `ImPlotOrientation`. 

Love it! Another thought: 

If we changed `ImPlotOrientation` to be a flag, then it could be possible to pass `ImPlotOrientation_Horizontal | ImPlotOrientatoin_Vertical` for 2D grids of plots. Is that overkill? 

Otherwise this looks great, I'll try to take a look tonight or tomorrow.

**Comment by ozlb** [comment]
> If we changed `ImPlotOrientation` to be a flag, then it could be possible to pass `ImPlotOrientation_Horizontal | ImPlotOrientatoin_Vertical` for 2D grids of plots. Is that overkill?

signature is ok, but to use as flag, enum `ImPlotOrientation_` need to be changed and start from 1.

```
// Used to orient items on a plot (e.g. legends, labels, etc.) or align plots
enum ImPlotOrientation_ {
    ImPlotOrientation_None       = 0,      // 
    ImPlotOrientation_Horizontal = 1 << 0, // left/right
    ImPlotOrientation_Vertical   = 1 << 1, // up/down
};

```
I cross check where is used for legends, labels and should not be problematic.

**Comment by ozlb** [comment]
Ready for your final approval / refinements / decorations.

**Comment by epezent** [comment]
@ozlb , sorry I haven't addressed this. I wanted to first merge organizational changes I've been making in `implot_internal.h` with the addition of `ImPlotFlags_Equal`. That's done, and so this needs to have a few conflicts resolved.

**Comment by ozlb** [comment]
I will resolve the conflicts and update PR.

**Comment by ozlb** [comment]
Done

**Comment by Mrgoodbytes13** [comment]
Would it be possible to also add crosshair alignment for plot groups?
ie:
aligned

**Comment by ozlb** [comment]
interesing, but before I need to sync to latest version so hopefully it will be merged into master.

**Comment by yamen** [comment]
I came here to look for a way to do this, and here's a PR with exactly what I need! This is fantastic work.

I think crosshair alignment should be covered separately, as it only depends on X-value linking, which already has a working solution. Once we get visual alignment of X-axis, the rest will work fine.

**Comment by epezent** [comment]
@yamen and @ozlb , I hope to integrate this soon. I know this a feature that many will enjoy. Sorry for the delay.

**Comment by arximboldi** [comment]
Oh yes!

**Comment by dgm3333** [comment]
Can I vote for the ozlb code getting pulled into the main branch - I've got a couple of plots I ended up aligning by modifying the axis text :-( but this would be much better.

**Comment by dgm3333** [comment]
Incidentally (as it's related to alignment)
There also seems to be an oddity I can't consistently replicate where if you don't call the SetNextPlotLimitsX before EVERY linked plot the xmin gets set to 0 for all of them (but it seems sometimes OK not to??).
Also I originally assumed you didn't have to manually call SetNextPlotLimitsX (as it's not in the original demo script), but this isn't the case - should the link ALSO call SetNextPlotLimitsX since xmin/max/etc are being set to a value?

if (ImGui::CollapsingHeader("Linked Axes")) {
    static double xmin = 10, xmax = 11, ymin = 0, ymax = 1;
    static bool linkx = true, linky = true;
    int data[2] = {0,1};
    int series[2] = { 10,11 };
    ImGui::Checkbox("Link X", &linkx);
    ImGui::SameLine();
    ImGui::Checkbox("Link Y", &linky);
    ImPlot::LinkNextPlotLimits(linkx ? &xmin : NULL , linkx ? &xmax : NULL, linky ? &ymin : NULL, linky ? &ymax : NULL);
    //ImPlot::SetNextPlotLimitsX(xmin, xmax, ImGuiCond_Once);
    if (ImPlot::BeginPlot("Plot A")) {
        ImPlot::PlotLine("Line",series,data,2);
        ImPlot::EndPlot();
    }
    ImPlot::LinkNextPlotLimits(linkx ? &xmin : NULL , linkx ? &xmax : NULL, linky ? &ymin : NULL, linky ? &ymax : NULL);
    //ImPlot::SetNextPlotLimitsX(xmin, xmax, ImGuiCond_Once);
    if (ImPlot::BeginPlot("Plot B")) {
        ImPlot::PlotLine("Line",series, data,2);
        ImPlot::EndPlot();
    }
}

(using latest imgui and implot compiling win64 c++20 under Visual Studio)

**Comment by epezent** [comment]
Merged as a part of #203

**Pull request closed without merging**
