### PR TITLE
SetNextPlotDragDisable

### PR DESCRIPTION
**Pull request by ozlb**
Set drag operations disable for the next plot. Call right before BeginPlot(). 
https://github.com/epezent/implot/issues/89#issuecomment-675132076

### CODE REVIEW

**Comment by epezent** [comment]
I understand what this does, but I don't understand why it's needed. Alternatively, the axis flags could be temporarily modified to include `ImPlotAxisFlags_LockMin` and `ImPlotAxisFlags_LockMax`. What particular problem are you trying to solve?

**Comment by ozlb** [comment]
Assume that you want to customize with "widget" a plot
Assume that you want to interact with that "widget" and drag it
a) you need to be after BeginPlot in order to get DrawList and to render it
b) drag of axis and query is inside BeginPlot so it's BEFORE the widget code
c) II need to lock axis but also potentially all other begin of drag operations, as the one mentioned from label or whatever will be in future

**Comment by epezent** [comment]
Ok, that makes sense. Let me think on this and make sure there isn't a better solution. I can see potential headaches with the approach you described. Needing widget logic/input detection before `BeginPlot`, then `SetNextPlotDragDisable` conditioned on that logic, and then widget rendering after `BeginPlot` seems a bit burdensome. Perhaps it's time to properly implement custom a widget/tooltip system. Maybe via callbacks?

**Comment by ozlb** [comment]
I’m with you that it’s not perfect. Callback could be a solution, you have a better vision of actual status and direction for future.

**Pull request closed without merging**
