### PR TITLE
Fix implicit double to float conversions.

### PR DESCRIPTION
**Pull request by exjam**
You do not include <cmath> in implot.cpp and instead rely on the include of math.h through the imgui_internal.h header - this C version of the header not have the float overloads leading to double to float conversion warnings.

### CODE REVIEW

**Comment by exjam** [comment]
Oh crap I just saw #37 is already open for this ...

**Comment by exjam** [comment]
Well I guess feel free to merge either one depending on the fix you prefer, whether that is include <cmath> or not.

**Comment by epezent** [comment]
Thanks. I'm currently working on some internal changes that will probably obviate this. I'll leave it open for now.

**Comment by epezent** [comment]
Hi, this should have been resolved by https://github.com/epezent/implot/commit/aa23d95e21cb261e933995891049ea8c8f213cd1

I checked this with all warnings on MSVC, GCC, and Clang, but do let me know if there are still issues.

**Pull request closed without merging**
