### PR TITLE
Vertical and Horizontal error bars

### LINKED ISSUE #57: Addition of horizontal error bars

### PR DESCRIPTION
**Pull request by ChiefSeaBiscuit**
Closes #57

### CODE REVIEW

**Comment by ChiefSeaBiscuit** [comment]
An example of the additional demo can be seen in #57

**Comment by epezent** [comment]
@ChiefSeaBiscuit, looks good. One suggestion: I don't think it's necessary for the horizontal version to also do the vertical rendering. If the user wants vertical and horizontal bars, they just make two function calls. Can you make PlotErrorBarsH only do horizontal? As such, you won't need `ImPlotPointErrorH `, as you can reuse `ImPlotPointError`.

**Comment by ChiefSeaBiscuit** [comment]
@epezent Ahh yeah true, that makes more sense now you say it! I'll try and get those changes in tonight or so!

**Comment by ChiefSeaBiscuit** [comment]
Added the changes, I've also altered the demo for it slightly just to highlight that positive and negative errors can be set individually as the developer might not be aware of this feature, from the original demo alone without looking at the function decs

image

**Pull request merged**
