### PR TITLE
warning fixes

### PR DESCRIPTION
**Pull request by sergeyn**
removed conversions from float to double and back. removed static text buffers, use of secure sprintf functions under visual studio, float-to-int conversions (please check that)

### CODE REVIEW

**Comment by epezent** [comment]
Hi, several of these issues were addressed in other commits, and a lot has changed since this was submitted. Would you mind merging master and seeing which issues still persist?

**Comment by sergeyn** [comment]
Ok, done.

**Comment by sergeyn** [comment]
can this PR get some love please ? thanks!

**Comment by epezent** [comment]
It's been given the love it deserved.

**Pull request merged**
