### PR TITLE
Handle possibly overlapping widgets added via ImGui::SetItemAllowOverlap()

### PR DESCRIPTION
**Pull request by bear24rw**
For my application I needed a horizontal reference line that could be adjusted by dragging it with the mouse. To do this I added an invisible button and detect when that button is being dragged. In order for this to work I needed to modify ImPlot to tell `ImGui::ItemAdd` what our ID is, and then check for if `HoveredIdPreviousFrame` matches our ID. If it does not match that indicates that the mouse is actually hovering a widget added on top of us. I'm not sure why `ImGui::ItemHoverable` does not check this by default?

I've included a demo of a horizontal line movable via click and drag.

### CODE REVIEW

**Comment by epezent** [comment]
Awesome! I had no idea it was possible to capture drag this way. This is an issue @ozlb has been talking about for a long time, also for dragable guides/line (#113, #98). This PR pretty much solves the main issue we were having -- disabling plot input when a user tool or widget is engaged.

The line/guide tool is so useful and requested, I may clean up and incorporate your demo code into the public API, e.g. `ImPlot::HorizontalGuide(const char* id, double* value)`. 

Stay tuned...

**Comment by ozlb** [comment]
Actually yes, it looks like we do have identical request (in my case 2 vertical lines)!

**Comment by epezent** [comment]
I just added the following:

```cpp
// Shows a draggable horizontal guide line.
IMPLOT_API bool HorizontalGuide(const char* id, double* value, const ImVec4& col = IMPLOT_AUTO_COL, float thickness = 2);
// Shows a draggable vertical guide line.
IMPLOT_API bool VerticalGuide(const char* id, double* value, const ImVec4& col = IMPLOT_AUTO_COL, float thickness = 2);
```

Demo:

```cpp
if (ImPlot::BeginPlot("##guides",0,0,ImVec2(-1,0),ImPlotFlags_YAxis2)) {            
    ImPlot::VerticalGuide("v1",&v1, ImVec4(0,1,0,1));
    ImPlot::VerticalGuide("v2",&v2, ImVec4(0,1,0,1));
    ImPlot::HorizontalGuide("h1",&h1, ImVec4(1,0,0,1));
    ImPlot::HorizontalGuide("h2",&h2, ImVec4(1,0,0,1));
    ImPlot::SetPlotYAxis(1);
    ImPlot::HorizontalGuide("h3",&h3, ImVec4(1,1,0,1));
    ImPlot::EndPlot();
}
```

guides


@ozlb , can you recommended any additional functionality? e.g. I was thinking it might be useful to display a tick label for the current value.

**Comment by bear24rw** [comment]
Thanks for the fast turn around getting a real api around it! Looks perfect for my use case. I think the tick label could easily be drawn by the user with PlotText()?

**Comment by ozlb** [comment]
> @ozlb , can you recommended any additional functionality? e.g. I was thinking it might be useful to display a tick label for the current value.

If you mean something similar to what @Prinkesh show in https://user-images.githubusercontent.com/5650130/83980205-720a7100-a931-11ea-9589-7283f57f7d77.gif (red label in x axis values), I think it will be very nice and if before the value there will be also the char *id that identifies the gudie (i.e. v1=0.3,  v2=0.7), even better!

One question: imagine that i would like to find the "closest" x[] and so [y] of a PlotLine relative o a vertical guide, how you suggest to find it? As per candlestick demo, with "binary search" strategies?

**Comment by epezent** [comment]
Added labels and a better demo. Thoughts?

guides

**Comment by epezent** [comment]
> One question: imagine that i would like to find the "closest" x[] and so [y] of a PlotLine relative o a vertical guide, how you suggest to find it? As per candlestick demo, with "binary search" strategies?

Something like that. I'd probably use `std::lower_bound` or `std::upper_bound` in practice.

**Comment by epezent** [comment]
We should also introduce an "anchor" tool -- essentially a point that is draggable in both dimensions. You could imagine using several of these as spline handles for timeline/animation editors, etc.

**Comment by bear24rw** [comment]
Love the label and the extra thick tick at the end, makes it stand out over a regular line. Draggable anchors would definitely be useful! I also wonder if you use this feature to make the query rect easily adjustable via click and drag.

**Comment by bear24rw** [comment]
Noticed a minor issue: when drawing the zoom box with right click + drag, when your mouse hovers over the guide lines it changes the cursor and shows the label.

**Comment by epezent** [comment]
> Noticed a minor issue: when drawing the zoom box with right click + drag, when your mouse hovers over the guide lines it changes the cursor and shows the label.

Fixed

**Comment by epezent** [comment]
Here's a prototype for anchors!

```cpp
// Shows a draggable anchor point. #col defaults to ImGuiCol_Text.
bool AnchorPoint(const char* id, double* x, double* y, const ImVec4& col = IMPLOT_AUTO_COL, float radius = 5);
```

anchor

**Comment by ozlb** [comment]
> We should also introduce an "anchor" tool -- essentially a point that is draggable in both dimensions. You could imagine using several of these as spline handles for timeline/animation editors, etc.

you can use also to pin an event during data recording or to notify an event... and since they are responding to `(ImGui::IsItemHovered() || ImGui::IsItemActive())` there are infinite solutions (i.e. trap double click to remove or change color or whatever interaction).
You "open a Pandora's box"...

**Comment by ozlb** [comment]
At the limit of the “off topic” comment.
With new API released after this PR I completely removed my “QueryX” implementation that i was maintaining during all this time for each new version of library. I’m very happy to use ImPlot in native way!

**Comment by epezent** [comment]
I'm glad we finally found a way to support this feature for you @ozlb! I'd like to see if we can migrate regular Query to this style (i.e. decouple from Begin/EndPlot and make it a separate "tool" function).

**Pull request merged**
